### PR TITLE
Add wallet by web3 react

### PR DESCRIPTION
**Pull request by ibex098**
Add wallet by web3-react

### CODE REVIEW

**Review by Zergity — CHANGES_REQUESTED** [review]
please find and link the external wallet logos, and remove unnessesary changes

**Review by Zergity — COMMENTED** [review]
image
 the buttons still have different sizes

**Review by Zergity — CHANGES_REQUESTED** [review]
detect the wallet availability and show the installation website when it's not available (e.g. for Frame, check connection to http://127.0.0.1:1248, and open https://frame.sh

**Comment by CaoThien96** [comment]
Commit [#5ba276f ](https://github.com/ezDeFi/web3-react-modal/pull/8/commits/5ba276f73db524b66f4a3bc33ddb51b242712d5e) to fix some case connect error  of issue #9

**Comment by Zergity** [comment]
please handle this case for Frame
1. install frame, remove all accounts
2. try to connect
3. nothing happen

**Review by Zergity — CHANGES_REQUESTED** [review]

**Comment by CaoThien96** [comment]
> Magic: this dialog is shown when user attempt to login

**Comment by CaoThien96** [comment]
> Frame: please handle this case:
> 
> 1. install frame, remove all accounts
> 2. try to connect
> 3. nothing happen
> 
> Ledge: try to connect without Ledge device -> nothing happen. Expect some dialog to show user that no device detect ... (please check the connector sample)
> 
> Magic: this dialog is shown when user attempt to login image

So with Frame, Ledger we just need to display the error that the library returns?

**Review by Zergity — CHANGES_REQUESTED** [review]
please commit the `.env` and your sample API key

**Review by Zergity — APPROVED** [review]
LGTM

**Pull request merged**
